spring:
  datasource:
    url: jdbc:mysql://localhost:3306/class-registration
    username: root
    password: fake-pass
  application:
    name: class-registration
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
